### ISSUE TITLE
building this package: tcl conflicts with itself

### ISSUE THREAD

**Issue by igalic** [lxc/lxd-pkg-snap#10]
Hey folks,

i made some modifications to the git repository, and thought the best way to easily reuse & test those would be via snap. For instance: conjure-up kubernetes wants lxd!

Unfortunately, i'm unable to build this snap on my local Ubuntu 17.10 machine, due to a dependency conflict in tcl:

```
snapcraft
Installing build dependencies: asciidoc asciidoc-base asciidoc-common asciidoc-dblatex asciidoc-doc dblatex dblatex-doc docbook-dsssl docbook-utils fonts-gfs-baskerville fonts-gfs-porson golang-1.8-go golang-1.8-race-detector-runtime golang-1.8-src golang-go golang-race-detector-runtime golang-src jadetex libblkid-dev libfuse-dev libnet1 libnet1-dev libnl-3-dev libosp5 libostyle1c2 libpam0g-dev libprotobuf-c-dev libsgmls-perl lynx lynx-common openjade opensp protobuf-c-compiler sgmlspl tcl tcl:i386 texlive-bibtex-extra texlive-formats-extra texlive-htmlxml texlive-lang-greek texlive-science texlive-science-doc texlive-xetex uuid-dev vim-addon-manager vim-asciidoc xmlto xsltproc                                                 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tcl is already the newest version (8.6.0+9).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tcl : Conflicts: tcl:i386
 tcl:i386 : Conflicts: tcl
E: Unable to correct problems, you have held broken packages.
```

I'm not *quite* sure why both of those are required, much less why they would conflict with each other, but here we are.

**Comment by igalic** [comment]
okay, so, i've traced this down to the [following line](https://github.com/snapcore/snapcraft/blob/master/snapcraft/internal/repo/_deb.py#L248)
it seems to be an issue in snapcraft itself, and the way it resolves virtual packages

**Comment by stgraber** [comment]
Closing as not a packaging issue itself. Note that we only ever build the LXD snap on Ubuntu 16.04.
We'll likely eventually switch to Ubuntu 18.04 as the base, but we're very unlikely to ever support building it on anything other than what we ourselves use to publish to the store.
