### ISSUE TITLE
chroot: cannot change root directory to '/var/lib/snapd/hostfs': Operation not permitted

### ISSUE THREAD

**Issue by fnordahl** [lxc/lxd-pkg-snap#2]
After refresh of lxd snap to 4375 one of my production systems showed the error message in the subject on lxd exec, lxc list etc.

Reverting to 4279 restored operation.

Will gather more information and try to provide reproducer.

**Comment by stgraber** [comment]
Hmm, that's odd, I wonder why the chroot operation is failing...

**Comment by stgraber** [comment]
@fnordahl what distribution is that on?

**Comment by fnordahl** [comment]
@stgraber Ubuntu 16.04

**Comment by stgraber** [comment]
@fnordahl can you paste the output of "snap list" and "snap version"?

**Comment by fnordahl** [comment]
$ snap list
Name  Version    Rev   Developer  Notes
core  16-2.27.6  2898  canonical  core
lxd   2.18       4279  canonical  -

$ snap version
snap    2.27.6
snapd   2.27.6
series  16
ubuntu  16.04
kernel  4.10.0-35-generic

**Comment by fnordahl** [comment]
$ ls -l /var/snap/lxd/
total 16
drwxr-xr-x 3 root root 4096 Jul 26 10:03 4197
drwxr-xr-x 3 root root 4096 Jul 26 10:03 4279
drwxr-xr-x 3 root root 4096 Jul 26 10:03 4375
drwxr-xr-x 6 root root 4096 Oct  4 06:08 common
lrwxrwxrwx 1 root root    4 Oct  4 06:08 current -> 4279

**Comment by fnordahl** [comment]
kern.log contains a lot of apparmor DENIED entries for lxd. These messages stopped after reverting the snap

**Comment by stgraber** [comment]
Can you share those? I wonder if the LXD snap somehow got disconnected from the lxd-support interface.

**Comment by fnordahl** [comment]
Excerpt, slightly anonymized. Can provide complete and verbatim log to you offline if you need.

Oct  4 03:26:00 hostname systemd[1]: Reloading.
Oct  4 03:26:00 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:00 hostname systemd[1]: Reloading.
Oct  4 03:26:00 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:00 hostname systemd[1]: Mounting Mount unit for lxd...
Oct  4 03:26:00 hostname systemd[1]: Mounted Mount unit for lxd.
Oct  4 03:26:00 hostname systemd[1]: Stopping Service for snap application lxd.daemon...
Oct  4 03:26:00 hostname kernel: [1163428.145128] audit: type=1400 audit(1507080360.756:1203): apparmor="DENIED" operation="open" profile="snap.lxd.daemon" name="/var/lib/snapd/hostfs/usr/lib/os-release" pid=4172 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Oct  4 03:26:00 hostname kernel: [1163428.145390] audit: type=1400 audit(1507080360.756:1204): apparmor="DENIED" operation="create" profile="snap.lxd.daemon" pid=4172 comm="snap-exec" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:00 hostname kernel: [1163428.145397] audit: type=1400 audit(1507080360.756:1205): apparmor="DENIED" operation="create" profile="snap.lxd.daemon" pid=4172 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:00 hostname kernel: [1163428.145401] audit: type=1400 audit(1507080360.756:1206): apparmor="DENIED" operation="create" profile="snap.lxd.daemon" pid=4172 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:00 hostname lxd.daemon[4172]: => Stop reason is: snap refresh
Oct  4 03:26:00 hostname lxd.daemon[4172]: => Stopping LXD
Oct  4 03:26:00 hostname kernel: [1163428.201721] audit: type=1400 audit(1507080360.812:1207): apparmor="DENIED" operation="open" profile="snap.lxd.lxc" name="/var/lib/snapd/hostfs/usr/lib/os-release" pid=4204 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct  4 03:26:00 hostname kernel: [1163428.201977] audit: type=1400 audit(1507080360.812:1208): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=4204 comm="snap-exec" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:00 hostname kernel: [1163428.201984] audit: type=1400 audit(1507080360.812:1209): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=4204 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:00 hostname kernel: [1163428.201988] audit: type=1400 audit(1507080360.812:1210): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=4204 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:00 hostname kernel: [1163428.220598] audit: type=1400 audit(1507080360.832:1211): apparmor="DENIED" operation="open" profile="snap.lxd.lxc" name="/var/lib/snapd/hostfs/usr/lib/os-release" pid=4219 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct  4 03:26:00 hostname kernel: [1163428.220847] audit: type=1400 audit(1507080360.832:1212): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=4219 comm="snap-exec" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:01 hostname systemd[1]: Stopped Service for snap application lxd.daemon.
Oct  4 03:26:02 hostname systemd[1]: Reloading.
Oct  4 03:26:02 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:02 hostname systemd[1]: Reloading.
Oct  4 03:26:02 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:03 hostname snapd[1103]: 2017/10/04 03:26:03.117705 helpers.go:206: cannot connect plug "home" from snap "lxd", no such plug
Oct  4 03:26:03 hostname systemd[1]: Reloading.
Oct  4 03:26:04 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:04 hostname systemd[1]: Reloading.
Oct  4 03:26:04 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:04 hostname systemd[1]: Started Service for snap application lxd.daemon.
Oct  4 03:26:04 hostname lxd.daemon[10672]: => Preparing the system
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Loading snap configuration
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Setting up modprobe wrapper
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Preparing a clean copy of /run
Oct  4 03:26:04 hostname systemd[1]: Unmounted Mount unit for lxd.
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Preparing a clean copy of /etc
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Setting up ceph configuration
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Setting up LVM configuration
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Escaping the systemd cgroups
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Escaping the systemd process resource limits
Oct  4 03:26:04 hostname lxd.daemon[10672]: ==> Enabling unprivileged containers kernel support
Oct  4 03:26:04 hostname lxd.daemon[10672]: => Re-using existing LXCFS
Oct  4 03:26:04 hostname lxd.daemon[10672]: => Starting LXD
Oct  4 03:26:04 hostname systemd[1]: Reloading.
Oct  4 03:26:04 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:04 hostname systemd[1]: Reloading.
Oct  4 03:26:04 hostname systemd[1]: Started ACPI event daemon.
Oct  4 03:26:04 hostname lxd.daemon[10672]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-10-04T01:26:04+0000
Oct  4 03:26:04 hostname dnsmasq-dhcp[9341]: router advertisement on fd42:1949:2bc7:aca2::, old prefix for lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[9341]: DHCPv6 stateless on fd42:1949:2bc7:aca2::, constructed for lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[9341]: DHCPv4-derived IPv6 names on fd42:1949:2bc7:aca2::, constructed for lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[9341]: router advertisement on fd42:1949:2bc7:aca2::, constructed for lxdbr0
Oct  4 03:26:04 hostname dnsmasq[11388]: started, version 2.75 cachesize 150
Oct  4 03:26:04 hostname dnsmasq[11388]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: DHCP, IP range 10.152.245.2 -- 10.152.245.254, lease time 1h
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: DHCPv6 stateless on lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: DHCPv4-derived IPv6 names on lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: router advertisement on lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: DHCPv6 stateless on fd42:1949:2bc7:aca2::, constructed for lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: DHCPv4-derived IPv6 names on fd42:1949:2bc7:aca2::, constructed for lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: router advertisement on fd42:1949:2bc7:aca2::, constructed for lxdbr0
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: IPv6 router advertisement enabled
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: DHCP, sockets bound exclusively to interface lxdbr0
Oct  4 03:26:04 hostname dnsmasq[11388]: using local addresses only for domain lxd
Oct  4 03:26:04 hostname dnsmasq[11388]: reading /etc/resolv.conf
Oct  4 03:26:04 hostname dnsmasq[11388]: using local addresses only for domain lxd
Oct  4 03:26:04 hostname dnsmasq[11388]: using nameserver 130.67.15.198#53
Oct  4 03:26:04 hostname dnsmasq[11388]: using nameserver 193.213.112.4#53
Oct  4 03:26:04 hostname dnsmasq[11388]: read /etc/hosts - 5 addresses
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/container1
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/container2
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/conatiner3
Oct  4 03:26:04 hostname dnsmasq[11388]: read /etc/hosts - 5 addresses
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/container1
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/container2
Oct  4 03:26:04 hostname dnsmasq-dhcp[11388]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/container3
Oct  4 03:26:05 hostname lxd.daemon[10672]: => LXD is ready
Oct  4 03:26:05 hostname kernel: [1163433.156284] kauditd_printk_skb: 576 callbacks suppressed
Oct  4 03:26:05 hostname kernel: [1163433.156285] audit: type=1400 audit(1507080365.768:1789): apparmor="DENIED" operation="open" profile="snap.lxd.lxc" name="/var/lib/snapd/hostfs/usr/lib/os-release" pid=11975 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct  4 03:26:05 hostname kernel: [1163433.156663] audit: type=1400 audit(1507080365.768:1790): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=11975 comm="snap-exec" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:05 hostname kernel: [1163433.157016] audit: type=1400 audit(1507080365.768:1791): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=11975 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:05 hostname kernel: [1163433.157052] audit: type=1400 audit(1507080365.768:1792): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=11975 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:05 hostname kernel: [1163433.175187] audit: type=1400 audit(1507080365.788:1793): apparmor="DENIED" operation="open" profile="snap.lxd.lxc" name="/var/lib/snapd/hostfs/usr/lib/os-release" pid=11988 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct  4 03:26:05 hostname kernel: [1163433.175509] audit: type=1400 audit(1507080365.788:1794): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=11988 comm="snap-exec" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:05 hostname kernel: [1163433.175554] audit: type=1400 audit(1507080365.788:1795): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=11988 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:05 hostname kernel: [1163433.175587] audit: type=1400 audit(1507080365.788:1796): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=11988 comm="snap-exec" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:05 hostname kernel: [1163433.194588] audit: type=1400 audit(1507080365.808:1797): apparmor="DENIED" operation="open" profile="snap.lxd.lxc" name="/var/lib/snapd/hostfs/usr/lib/os-release" pid=12001 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct  4 03:26:05 hostname kernel: [1163433.194920] audit: type=1400 audit(1507080365.808:1798): apparmor="DENIED" operation="create" profile="snap.lxd.lxc" pid=12001 comm="snap-exec" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Oct  4 03:26:10 hostname kernel: [1163438.164187] kauditd_printk_skb: 1178 callbacks suppressed
(and it continues like this)

**Comment by stgraber** [comment]
Ok, those matches what I see locally. Those come from snap-confine itself and other than spamming the logs, are harmless. Looks like the snapd guys forgot to update the snap-confine apparmor profile when they added extra logic to it recently.

Those don't explain the chroot failure you're getting. I've also been unable to reproduce it here even after I switch my test machine's kernel to match yours.

What I did however is add code to the wrapper so that if chroot is going to fail, it simply won't do it and go through the old code path. This means you won't get access to any path on the filesystem (which is what the chroot wrapper gets you) but at least the command will otherwise work fine.

**Comment by fnordahl** [comment]
@stgraber thx for swift response and action. Will try to provide analysis/reproducer for the chroot failure seen on this system in case it needs further analysis.
