### ISSUE TITLE
Any way to get `lxc edit` commands respect vimrc?

### ISSUE THREAD

**Issue by iBug** [lxc/lxd-pkg-snap#37]
I'm using `snap install lxd` as my LXD installation and every time I edit config and profile, there's no `vimrc` loaded and I'm unproductive with the clumsy "default" Vim. Any chance I could get `vimrc` loaded with the bundled Vim editor? Or any chance I could use my own Vim installed in the host OS?

**Comment by stgraber** [comment]
Can you try copying your vim config to ~/snap/lxd/current/ ?
That's the home directory that the snap sees so should load from there.

**Comment by iBug** [comment]
I did but it didn't seem to have any effect:

```shell
root@localhost:~# cat $HOME/snap/lxd/current/.vimrc
set showcmd number ruler
root@localhost:~#
```

Now I launch `lxc config edit default` and don't see line numbers, which I suppose very well means that the `.vimrc` file isn't loaded.

**Comment by vyalyh-oleg** [comment]
`lxc config edit` and so on don't respect .vimrc, .viminfo on Ubuntu 20.04.
After copying into (~/snap/lxd/current/.vimrc ) the editing with `lxc config edit` isn't posiible, because the Backspace became broken.

**Comment by stgraber** [comment]
Keep in mind that it is vim-tiny that we have in the snap, it doesn't support a lot of things and is why we don't use the user's or the system's vimrc and instead have you provide a separate vimrc.
