### ISSUE TITLE
daemon.start crashes when LD_LIBRARY_PATH is not set

### ISSUE THREAD

**Issue by JulianLiu** [lxc/lxd-pkg-snap#4]
Somehow in my system variable LD_LIBRARY_PATH is not set when lxd daemon starts and will crash daemon.start.
https://github.com/lxc/lxd-pkg-snap/blob/latest-edge/snapcraft/wrappers/daemon.start#L16

Maybe it need a check on LD_LIBRARY_PATH before appending path to it?

Log:
```
Dec 18 09:53:12 localhost systemd[1]: Started Service for snap application lxd.daemon.
Dec 18 09:53:13 localhost lxd.daemon[1854]: => Preparing the system
Dec 18 09:53:13 localhost lxd.daemon[1854]: /snap/lxd/5316/wrappers/daemon.start: 16: /snap/lxd/5316/wrappers/daemon.start: LD_LIBRARY_PATH: parameter not set
Dec 18 09:53:13 localhost systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 18 09:53:13 localhost lxd.daemon[1869]: => Stop reason is: crashed
```

**Comment by stgraber** [comment]
What operating system are you running?

**Comment by stgraber** [comment]
We've had report of this for people using debian testing/unstable after apparmor was enabled, apparently snapd is broken on such systems, but we don't actively track/test this as those aren't stable releases of Debian.

**Comment by JulianLiu** [comment]
ah..  I'm running Ubuntu Core 16 with customized kernel apparmor enabled.
I think that is the problem.
Thank you for pointing out the direction.
