### ISSUE TITLE
Cannot remove lxd snap: read-only file system

### ISSUE THREAD

**Issue by adamryczkowski** [lxc/lxd-pkg-snap#46]
* Distribution: Ubuntu
 * Distribution version:  18.04.4 (hwe)
 * The output of "lxc info" or if that fails:
*`lxc` cannot be executed because of this error*
   * Kernel version: `5.0.0-37-generic`
   * LXC version: pretty current, snap was refreshed no earlier than few weeks ago
   * LXD version: as above
   * Storage backend in use: btrfs

# Issue description

I ran into problems with lxc so decided to reinstall it. Unfortunately the `sudo snap remove lxd` fails with the following error:

```
$ sudo snap remove lxd
error: cannot perform the following tasks:
- Remove data for snap "lxd" (12317) (remove /var/snap/lxd/common/lxd/storage-pools/default/images/979ff60086ca9fb1c93d3131f8eca291820a524f0bd0b7d621a3c2f5f41ef185/metadata.yaml: read-only file system)
```

Please note, that in fact the filesystem is **not** read only:

```
$ sudo btrfs property get -ts /var/snap/lxd/common/lxd/storage-pools/default
ro=false
$ sudo btrfs property get -ts /var/snap/lxd/common/lxd/storage-pools/default/images
ro=false
```

# Steps to reproduce
I don't know. All other 4 systems where I use lxd(c) behave normally.

**Comment by darkdragon-001** [comment]
I am having the same problem on Ubuntu 20.04 also on Btrfs.
@stgraber Can you reopen it?

There is a workaround posted in the [forum](https://forum.snapcraft.io/t/unable-to-remove-lxd-read-only-file-system/16511):
Run (use the path from the error message without the `metadata.yml` part): 

    sudo btrfs subvolume delete /var/snap/lxd/common/lxd/storage-pools/default/images/979ff60086ca9fb1c93d3131f8eca291820a524f0bd0b7d621a3c2f5f41ef185

**Comment by stgraber** [comment]
LXD can only be cleanly removed if all instances, images and storage volumes have been deleted.

The errors here suggest it's a busy LXD being removed with complex leftover filesystem and kernel state.

This isn't something that snap remove can really handle on its own and unfortunately there isn't a good way for us in the packaging to prevent removal of such a busy installation.

**Comment by darkdragon-001** [comment]
This is exactly what I want to do: completely remove everything. Since I never created any volume manually, but snapd created it instead, I expect snapd to clean up as well. Detecting a running instance and stopping it (or at least telling the user _how_ to stop it) doesn't seem impossible for snapd as well.
