### ISSUE TITLE
Why tools have been disabled?

### ISSUE THREAD

**Issue by mdone-cloudian** [lxc/lxd-pkg-snap#47]
I noticed that you have `--disable-tools` among the configure options:

https://github.com/lxc/lxd-pkg-snap/blob/latest-edge/snapcraft.yaml#L670

Most of LXC's docs use those tools extensively, and the `lxc [command]` equivalents sometimes lack all the features of `lxc-command`. See https://linuxcontainers.org/lxc/getting-started/ for instance.

I'm particularly looking at `lxc start` vs `lxc-start`. Debug sesions like the ones at the end of this comment are impossible:

https://github.com/lxc/lxc/issues/3183#issue-520675512

Is there a reason for this? Can this be reverted, pretty pretty please?

**Comment by stgraber** [comment]
LXC and LXD aren't the same thing.
LXD is a daemon with a rest API and a client (`lxc`).

The LXC tools as `lxc-*` do not understand LXD and cannot be used at all in this environment.
If you want to use LXC itself, packages are available in most Linux distributions.

(yes the fact that the LXD client is called `lxc` is a bit confusing but that wasn't up to us :))

**Comment by mdone-cloudian** [comment]
Ok, but

> LXD isn't a rewrite of LXC, in fact it's building on top of LXC to provide a new, better user experience. Under the hood, LXD uses LXC through liblxc and its Go binding to create and manage the containers.

So LXC is still installed/used, right? An the line I linked is about configuring LXC, or is it the LXD client `lxc`? Can't we also get the `lxc-*` tools? Can't those tools understand the LXC side of the LXD stack? More specifically, can or can't I start a container built by LXD with `lxc-start`?

**Comment by stgraber** [comment]
LXD drives liblxc, that is, the C library at the heart of traditional LXC. It doesn't use any of the tools, configurations or paths that LXC provides.
