### ISSUE TITLE
Bash completions should consider the dynamic loading /usr/share path

### ISSUE THREAD

**Issue by BobVul** [lxc/lxd-pkg-snap#48]
In recent Debian, including Debian Buster, `/etc/bash_completion.d/` is considered obsolete. The directory isn't even created on a clean Buster install, which means the `lxd` snap package does not install completion scripts. It's possible to force it by manually creating that directory, but that's not obvious and takes a bit of digging to figure out why completions aren't working.

Here's part of the effort to remove `/etc/bash_completion.d/` entries from Debian packages: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776954

I think it'd be nice if the `lxd` package could preferentially use `/usr/share/bash-completion/completions` if it exists.

This seems to be handled at https://github.com/lxc/lxd-pkg-snap/blob/24cb299db411bd6c62e0daf4cfa693bca6c9c45c/snapcraft/commands/daemon.start#L172-L181 and https://github.com/lxc/lxd-pkg-snap/blob/24cb299db411bd6c62e0daf4cfa693bca6c9c45c/snapcraft/commands/daemon.start#L172-L181

Not sure if this is relevant: https://github.com/lxc/lxd-pkg-snap/blob/a29282723525d90d9d04fa299e5d7d10ed6353a1/snapcraft.yaml#L831-L834

**Comment by BobVul** [comment]
...actually I'm now unsure if it's as easy as dumping the completion script in the other directory, or if there are changes required. The dynamic loading [might be incompatible](https://unix.stackexchange.com/questions/216748/how-to-re-use-existing-completion-with-recent-bash-completion) with existing scripts? It's surprisingly hard to find authoritative documentation on this.

**Comment by BobVul** [comment]
Thanks for looking into this.

Unfortunately I've just noticed I double-linked daemon.start rather than linking daemon.stop as I intended in the original comment. So there's no scripted removal.

And now that I'm testing further, it looks like snapd might already create the `lxc` link in `/usr/share` on Buster? Very confused why it didn't do that in previous testing. Would make this fairly redundant if snapd is doing the right thing already.

Sorry about the waste of time 😐

**Comment by stgraber** [comment]
snapd is supposed to be handling part of this on its own too, yeah, though it's not been 100% reliable in our experience which is why we're also doing it ourselves directly.

**Comment by stgraber** [comment]
Updated removal logic to match

**Comment by BobVul** [comment]
Ah, that unreliability might explain why it worked in one test but not another.

Thanks again for looking into this.
