### ISSUE TITLE
lxc : sanity timeout expired: Interrupted system call

### ISSUE THREAD

**Issue by ozion92** [lxc/lxd-pkg-snap#49]
# Required information

 * Distribution: Debian
 * Distribution version: buster 10.0
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.37-5 
   * LXC version:
   * LXD version: 3.19 (snap, revision 13129)
   * Storage backend in use: zfs 

# Issue description

No lxc command available ; every lxc command hangs and after approx. 60s, it fails with the following error message : 

sanity timeout expired: Interrupted system call
cannot read from eventfd: Interrupted system call

It happened without particular reason. At one moment, we realized that some containers were not responsive ; one of the container had a very high cpu load. We connected on it by ssh and stopped the service, but it changed nothing ; we stopped the container, so the cpu load was fine again, but lxc was still not working. 

When we restart snap daemon (systemctl restart snap.lxd.daemon) the commend executes with no logs, but we have a snap-confine process with a cpu load of 100%.

 
# Steps to reproduce

 Don't know how to reproduce or what may have caused the issue. 

# Information to attach
Result of : cat /var/snap/lxd/common/lxd/logs/lxd.log

t=2020-01-26T13:06:32+0100 lvl=info msg="LXD 3.19 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2020-01-26T13:06:32+0100 lvl=info msg="Kernel uid/gid map:" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - u 0 0 4294967295" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - g 0 0 4294967295" 
t=2020-01-26T13:06:32+0100 lvl=info msg="Configured LXD uid/gid map:" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - u 0 1000000 1000000000" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - g 0 1000000 1000000000" 
t=2020-01-26T13:06:32+0100 lvl=info msg="Kernel features:" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - netnsid-based network retrieval: no" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - uevent injection: yes" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - seccomp listener: no" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - seccomp listener continue syscalls: no" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - cgroup layout: hybrid" 
t=2020-01-26T13:06:32+0100 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored" 
t=2020-01-26T13:06:32+0100 lvl=info msg=" - shiftfs support: disabled" 
t=2020-01-26T13:06:32+0100 lvl=info msg="Initializing local database" 
t=2020-01-26T13:06:33+0100 lvl=info msg="Starting /dev/lxd handler:" 
t=2020-01-26T13:06:33+0100 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2020-01-26T13:06:33+0100 lvl=info msg="REST API daemon:" 
t=2020-01-26T13:06:33+0100 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2020-01-26T13:06:33+0100 lvl=info msg=" - binding TCP socket" socket=[::]:8443
t=2020-01-26T13:06:33+0100 lvl=info msg="Initializing global database" 
t=2020-01-26T13:06:33+0100 lvl=info msg="Initializing storage pools" 
t=2020-01-26T13:06:33+0100 lvl=info msg="Applying patch: storage_zfs_mount" 
t=2020-01-26T13:09:17+0100 lvl=eror msg="Failed to start the daemon: Failed to run: zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/lxdstorage/containers/lxc00011 canmount=noauto zpool00/containers/lxc00011: umount: /var/snap/lxd/common/lxd/storage-pools/lxdstorage/containers/lxc00011: target is busy\n        (In some cases useful info about processes that\n         use the device is found by lsof(8) or fuser(1).)\ncannot unmount '/var/snap/lxd/common/lxd/storage-pools/lxdstorage/containers/lxc00011': umount failed" 
t=2020-01-26T13:09:17+0100 lvl=info msg="Starting shutdown sequence" 
t=2020-01-26T13:09:17+0100 lvl=info msg="Stopping REST API handler:" 
t=2020-01-26T13:09:17+0100 lvl=info msg=" - closing socket" socket=[::]:8443
t=2020-01-26T13:09:18+0100 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2020-01-26T13:09:18+0100 lvl=info msg="Stopping /dev/lxd handler:" 
t=2020-01-26T13:09:18+0100 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2020-01-26T13:09:18+0100 lvl=info msg="Closing the database" 

This error was in the log, but i don't think it is linked, it's an old error that happened 2 days ago. 
Now the snap/lxd log remains empty when we restart the daemon. 

The storage is zfs.
Result of ls -lh /var/snap/lxd/common/lxd/storage-pools/
drwx--x--x 1 root root 200 janv. 23 18:40 lxdstorage
drwx------ 1 root root  40 oct.   5 08:00 zpool00

**Comment by stgraber** [comment]
Moving issue over to the snap repo.

**Comment by ozion92** [comment]
Hi, the server was restarted last friday, everything was fine after the reboot, and everything is fine by now. Unfortunately we don't have any more idea about what happened.

**Comment by stgraber** [comment]
Odd. Let's close the issue for now. If you or anyone else runs into that again we'll reopen and try to reproduce so we can see what's going on.
