### ISSUE TITLE
Consider shipping a .vimrc with nicer defaults

### ISSUE THREAD

**Issue by BobVul** [lxc/lxd-pkg-snap#51]
The snap only includes `vim-tiny`, a fair choice considering the full `vim` is some 33 MB.

`vim-tiny` is supposed to default to a more Vi-like experience, so does not include some of the configuration options that `vim` ships with. The ones I've noticed include:

* Escape sequences (`esckeys`, including arrow keys and Home/End) in insert mode (covered by `compatible`)
* Multi-step history/undo (covered by `compatible`)
* Backspaces

Please consider including some of the Vim options (that the `vim` package ships with) to enable a more intuitive Vim experience.

The specific options that can go in `.vimrc` are:

```
" 'compatible' is Vi-compatible mode, disabled by the full vim package by default
"set nocompatible

" Enable backspaces in insert mode
set backspace=indent,eol,start
```

There is no actual need to set `compatible`/`nocompatible` as the existence of a `.vimrc` causes Vim to go into `nocompatible` mode.

---

While it's possible to configure these locally via a custom `.vimrc` as per #37, it'd be nice if they could be made default in new setups.

**Comment by stgraber** [comment]
The default config we ship actually has all of those bits set, the problem is that if we detect the host has its own config, we're using that instead of the one we bundle.

I've pushed a commit which now disables the attempt to parse the host config.

**Comment by BobVul** [comment]
Hm, interesting. Maybe taking the host `/etc/vim/vimrc` is appropriate but not the host `/etc/vim/vimrc.tiny`? Assuming the nicer non-Vi-compatible config is preferred. My host definitely has a good `/etc/vim/vimrc`.

But then there's the possibility of the host one not working on the smaller `vim-tiny` package if it uses plugins not available on it? Hm.

**Comment by stgraber** [comment]
From what I remember, I tried this but vim-tiny is too limited to process the full /etc/vim/vimrc, so yeah, that was an issue :)

Instead what we ship as vimrc is the Debian's default for vim-tiny which is as close as full vim behavior as can be achieved with tiny I believe.
