### ISSUE TITLE
Building lxd snap on amd64 for armhf?

### ISSUE THREAD

**Issue by ykoehler** [lxc/lxd-pkg-snap#58]
Hi,

I would like to customize the snap for testing and build an armhf version of it.  Right now every time I run snapcraft I get an amd64.  I tried adding the 

```
architectures:
  - build-on: amd64
    run-on: armhf
```

in combination with snapcraft build --target-arch armhf, it still doesn't go and cross-compile.

Instruction in the README on how to do so would be quite appreciated.

**Comment by stgraber** [comment]
It's not something we support, all our snaps are built on native architectures.

We include dozens of different packages and components from packages and from source and actually need to run some of them during the build, so cross-compilation isn't an option here.
