### ISSUE TITLE
Document the list of snapctl properties in the description of the LXD snap

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd-pkg-snap#6]
Title kinda says it all, we have a number of snap properties that we should document somewhere people can ifnd.

**Comment by dnegreira** [comment]
Shall I do a PR to create a snap.md in https://github.com/lxc/lxd/tree/master/doc describing how to install LXD via snapd and all the available proprieties as well as create a second PR to add a README.md on this repository pointing to the snaps URL at https://lxd.readthedocs.io?

**Comment by stgraber** [comment]
@dnegreira the main README for lxd should cover installation with the snap. The snap properties are effectively packaging details so I don't think it'd be appropriate to have that in the main LXD doc.

It'd make more sense to have it in snapcraft.yaml so that the store entry and `snap info` both show the available properties.

**Comment by dnegreira** [comment]
Then the only appropriate place should be under the `description` key on snapcraft.yaml, which seems a bit odd.
AFAICT snap doesn't support parsing the configuration parameters supported by snap and displaying them with `snap info`.

**Comment by stgraber** [comment]
Yeah, it'll go in the description. It's not ideal but it's the only place that's going to be shown on all systems that use the snap and the only place that's track-specific (as we don't have the same properties for the latest and 2.0 tracks).
