### ISSUE TITLE
`lxd.migrate` of empty servers often blocks for 10 minutes on GitHub Action runners

### ISSUE THREAD

**Issue by Saviq** [lxc/lxd-pkg-snap#63]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.4 LTS
 * [The output of "lxc info"](https://github.com/lxc/lxd/files/5097173/lxd_info.txt)

# Issue description

When running `lxd.migrate` on an empty / uninited LXD installation in GitHub Actions, removing the packages most often takes around 10 minutes.

It is the removal of lxd / lxd-client that lasts this long:
```
Start-Date: 2020-08-19  14:11:00
Commandline: apt-get remove --purge --yes lxd lxd-client
Requested-By: runner (1001)
Purge: lxd:amd64 (3.0.3-0ubuntu1~18.04.1), lxd-client:amd64 (3.0.3-0ubuntu1~18.04.1)
End-Date: 2020-08-19  14:21:06
```

The same removal prior to migration takes just 9s:
```
Wed, 19 Aug 2020 12:58:13 GMT $ sudo apt-get remove --purge --yes lxd lxd-client -o APT::Status-Fd=2 >/dev/null
Wed, 19 Aug 2020 12:58:17 GMT pmstatus:dpkg-exec:0.0000:Running dpkg
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd:0.0000:Removing lxd (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd:9.0909:Preparing for removal of lxd (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd:18.1818:Removing lxd (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd:27.2727:Removed lxd (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd:36.3636:Preparing to completely remove lxd (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd-client:36.3636:Removing lxd-client (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd-client:45.4545:Preparing for removal of lxd-client (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd-client:54.5455:Removing lxd-client (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd-client:63.6364:Removed lxd-client (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd-client:72.7273:Preparing to completely remove lxd-client (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:lxd-client:81.8182:Completely removed lxd-client (amd64)
Wed, 19 Aug 2020 12:58:18 GMT pmstatus:dpkg-exec:81.8182:Running dpkg
Wed, 19 Aug 2020 12:58:20 GMT pmstatus:dpkg-exec:81.8182:Running dpkg
Wed, 19 Aug 2020 12:58:20 GMT pmstatus:lxd:81.8182:Completely removing lxd (amd64)
Wed, 19 Aug 2020 12:58:21 GMT pmstatus:lxd:90.9091:Completely removed lxd (amd64)
Wed, 19 Aug 2020 12:58:21 GMT pmstatus:dpkg-exec:90.9091:Running dpkg
```

# Steps to reproduce

 1. run [this](https://github.com/Saviq/multipass/actions/runs/215302907/workflow) GitHub Workflow

# Information to attach

 - [x] [Main daemon log](https://github.com/lxc/lxd/files/5097201/lxd.log)
 - more detail can be found on [the workflow page](https://github.com/Saviq/multipass/actions/runs/215302907)

**Comment by Saviq** [comment]
OK [got it](https://github.com/Saviq/multipass/runs/1004590074), the 10 minutes are spent between those two:

```
Aug 19 19:24:10 pmstatus:lxd:9.0909:Preparing for removal of lxd (amd64)
Aug 19 19:34:10 pmstatus:lxd:18.1818:Removing lxd (amd64)
```

And the two corresponding journalctl events:
```
Aug 19 19:24:10 fv-az16 lxd[3208]: t=2020-08-19T19:24:10+0000 lvl=info msg="Saved simplestreams cache"
Aug 19 19:34:10 fv-az16 systemd[1]: Starting LXD - main daemon...
```

It's as if the daemon exiting takes the 10 minutes, which is weird since systemd should've killed it by then…

**Comment by stgraber** [comment]
Yeah, also odd because lxd.migrate itself has logic to forcefully kill the unit after 10s of wait time.

**Comment by Saviq** [comment]
@stgraber anything else I can provide? This still has the Incomplete label?

**Comment by stgraber** [comment]
Do you have more history on the slow package removal case? I'm wondering why our logic to kill the running LXD after 10s doesn't work for you.

Also getting a ps faux and systemctl -a output during those 10min would help confirm what's stuck.

**Comment by Saviq** [comment]
> Do you have more history on the slow package removal case? I'm wondering why our logic to kill the running LXD after 10s doesn't work for you.

More history of what? `apt-get` logs with status are [here](https://github.com/Saviq/multipass/runs/1004590074?check_suite_focus=true#step:11:1), and LXD logs are [here](https://github.com/Saviq/multipass/runs/1004590074?check_suite_focus=true#step:8:1).

> Also getting a ps faux and systemctl -a output during those 10min would help confirm what's stuck.

LXD related processes 6 seconds before it completes:
```
2020-09-07T10:38:24.2623481Z root       1222  0.0  0.0 161072  1536 ?        Ssl  10:26   0:00 /usr/bin/lxcfs /var/lib/lxcfs/
# ...
2020-09-07T10:38:24.2626437Z root       4227  0.0  0.0   4636  1848 ?        Ss   10:28   0:00 /bin/sh /snap/lxd/16926/commands/daemon.start
2020-09-07T10:38:24.2626811Z root       4404  0.1  0.7 1576028 55492 ?       SLl  10:28   0:00  \_ lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
2020-09-07T10:38:24.2627336Z root       4391  0.0  0.0  97804  1708 ?        Sl   10:28   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
2020-09-07T10:38:24.2627465Z root       4491  0.0  0.2 454704 21036 ?        Ssl  10:28   0:00 /usr/lib/lxd/lxd shutdown
2020-09-07T10:38:30.4115666Z Removing lxd dnsmasq configuration
```

As far I can tell, there's no change to that list for the 10 minutes it's stuck.

**Comment by stgraber** [comment]
@Saviq can you give `latest/edge` a try? I've reworked the background routine which kills the old systemd units so it's quite a bit more aggressive, hopefully that helps.

**Comment by Saviq** [comment]
Yup. This made it go :)
