### ISSUE TITLE
Downloading snaps if server is unavailable

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd-pkg-snap#76]
hi,

How can we create a local mirror of the snap repository?
We would like to do that in order to make them independent from the original source so even if it's unavailable, we still can deploy LXD with no problem.

With apt it was quite easy to solve this problem, but which snap it's not that obvious.

**Comment by tomponline** [comment]
Take a look at https://discuss.linuxcontainers.org/t/managing-the-lxd-snap/8178

I think the snap store proxy may be of use in this situation.

**Comment by stgraber** [comment]
An alternative to running a full proxy could also be using `snap download` to fetch the snaps and then `snap ack` and `snap install` to perform the offline installation.

**Comment by tomposmiko** [comment]
As per my understanding, snap store proxy is really a proxy with its limitation. Eg. there is a cache has a retention time. Am I correct about that?

Will check both solutions. Though, for the time being, I still like the old-school deb packages more. Easier to debug, more portable, it's simpler.
However, I also understand the benefits of the snap system.

**Comment by stgraber** [comment]
Not quite. The snap proxy does act as a proxy by default, keeping a copy of the snaps downloaded by your users to reduce the bandwidth usage. But it also allows you to pin a specific revision for any snap and channel you want.

It can also run completely offline with you manually importing the snaps you want into it.

**Comment by stgraber** [comment]
```
root@snap-proxy01:~# snap-store-proxy
usage: snap-proxy [-h] [-d] COMMAND ...

A smart caching proxy for the Snap Store

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           show debug logs and stacktraces

  COMMAND
    config              Configure snapstore.
    use-ca-certs        Import CA certificate bundle from stdin (PEM format)
    remove-ca-certs     Remove CA certificate bundle
    import-certificate  Load TLS certificates securely.
    register            Register the store.
    reregister          Clear the store id and rerun register with the same
                        args
    status (registration)
                        Get the status of this store.
    list-overrides      List channel map overrides.
    override            Set channel map overrides.
    delete-override     Delete channel map overrides.
    add-admin           Add a proxy admin.
    remove-admin        Remove a proxy admin.
    generate-keys       Generate proxy keys.
    create-database     Create the database
    check-connections   Run conn-check to test outgoing connections to
                        services
    enable-airgap-mode  Enable airgapped operations
    disable-airgap-mode
                        Disable airgapped operations
    push-snap           Push a snap to this air-gapped store.
    fetch-snaps         Download a list of snaps including blobs and
                        assertions
```

Should get you a rough idea of what it can do. Its doc may help too: https://docs.ubuntu.com/snap-store-proxy/en/ (looks a bit outdated especially around airgap/offline mode).
