### ISSUE TITLE
lxd.migrate due to upgrade from bionic->focal in an LXD container "breaks" do-release-upgrade

### ISSUE THREAD

**Issue by ajkavanagh** [lxc/lxd-pkg-snap#77]
# Required information

 * Distribution: Ubuntu 18.04 LTS

# Issue description

- In an bionic LXD container with update // upgrade done.
- host is bionic, with LXD containers. ^^
- do-release-upgrade from bionic -> focal in the container
- lxd deb pkg upgrades, and that installs snap --channel=stable/4.0
- lxd.migrate breaks/hangs/fails and then do-release-upgrade fails.

# Mitigation

Did

- apt purge lxd lxd-client before do-release-upgrade as LXD isn't needed in the containers.

**Comment by stgraber** [comment]
Moving to the `lxd-pkg-snap` repository.

I've tried reproducing it here with:
 - lxc launch ubuntu:18.04 u1
 - lxc exec u1 -- apt-get update
 - lxc exec u1 -- apt-get dist-upgrade
 - lxc exec u1 -- do-release-upgrade

This worked properly here, I got the prompt to select the snap channel and the 4.0/stable snap installed properly.

**Comment by gmeszaros** [comment]
I'm going through a similar upgrade process and have gone through containers with LXD deb package originally installed in them. I noticed that in some units (about half of them) have n after the Waiting for LXD to be online line, the others don't.
Also I have used do-release-upgrade with -f DistUpgradeViewNonInteractive and specified the DPKG::options { '--force-confdef'; '--force-confnew'; } to apt aforehand.

```
Preparing to unpack .../0-lxd_1%3a0.9_all.deb ...
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket
=> Installing the LXD snap
==> Checking connectivity with the snap store
==> Installing the LXD snap from the 4.0 track for ubuntu-20.04
2021-09-03T05:35:21Z INFO Waiting for automatic snapd restart...
lxd (4.0/stable) 4.0.7 from Canonical installed
==> Waiting for LXD to be online (10min timeout)
n
==> Running migration from Deb to Snap
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks
The source server is empty, no migration needed.
=> Snap installation complete
==> Cleaning up leftovers
```
