### ISSUE TITLE
xfs support to snap

### ISSUE THREAD

**Issue by esosan** [lxc/lxd-pkg-snap#8]
Hello, I'm using LVM (thin provisioning) and as filesystem I use xfs. It's possible to add mkfs.xfs to the snap version?

**Comment by stgraber** [comment]
Oh yeah, we can definitely do that.

**Comment by esosan** [comment]
Great! Thank you.
In the meanwhile... you have some suggestion/workaround how to use xfs? Or just build another storage?

**Comment by stgraber** [comment]
I can't think of any workaround until the tool is added and even though that's a trivial fix, it's going to be stuck on the Launchpad buildfarm currently being offline due to Meltdown/Spectre... once it's back online, we should have an updated snap within a few hours.

**Comment by esosan** [comment]
Hi, I just check the new release (5447) but I still have some trouble with XFS.
/snap/lxd/5447/bin/xfs_admin: 1: eval: xfs_db: not found

**Comment by stgraber** [comment]
doh, will add that one too :)

**Comment by stgraber** [comment]
Fix pushed to include all of xfs_* that should fix this. It'll be a few hours before that makes it to stable though.

**Comment by esosan** [comment]
Great! Thank you very much!

**Comment by stgraber** [comment]
@esosan any better now? the updated snap should be in the stable channel.

**Comment by esosan** [comment]
@stgraber now xfs it's working correctly. Thank you very much
