### ISSUE TITLE
networking not working on fresh lxd install

### ISSUE THREAD

**Issue by dstathis** [lxc/lxd-pkg-snap#80]
I just installed lxd using the snap on a relatively new Ubuntu 21.04 install. It looks like my containers can't reach the outside network. `lxc exec test1 ping 8.8.8.8` is just hanging forever. Let me know if there is any info I can provide that would be helpful.

**Comment by stgraber** [comment]
@dstathis most likely ou have ufw or similar in your instance configured to block all traffic

**Comment by dstathis** [comment]
So it turns out a reboot of the host ended up fixing this
