### ISSUE TITLE
wrong group for lxd control socket

### ISSUE THREAD

**Issue by hadmut** [lxc/lxd-pkg-snap#81]
* Distribution: Lubuntu
 * Distribution version: 20.04  
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

snap list lxd
Name  Version  Rev    Tracking       Publisher   Notes
lxd   4.17     21260  latest/stable  canonical✓  -

I'm having a service group lxd and put myself into this group in order to control LXD as a regular users. Used to work for years. 

Now I noticed and observerd several times a particular problem: 

After booting the host machine, I can't use the lxc command and access the socket as a regular user, because it doesn't have the correct group:

% ls -lF /var/snap/lxd/common/lxd/unix.socket 
srw-rw---- 1 root root 0 Aug 19 10:30 /var/snap/lxd/common/lxd/unix.socket=
                       
Notice: owner=root group=root

Then just a 
sudo snap stop lxd
sudo snap start lxd

and voila:
% ls -lF /var/snap/lxd/common/lxd/unix.socket
srw-rw---- 1 root lxd 0 Aug 19 17:55 /var/snap/lxd/common/lxd/unix.socket=

Notice: owner=root but now group=lxd

now I can use lxc as non-root , as usual. 

fgrep lxd /etc/group
lxd:x:129:hadmut

**Comment by stgraber** [comment]
Moving to the snap repo as that's where this is done.

The last time I saw this behavior, it was because for some reason the snap had deactivated our `snap.lxd.activate` unit which is the one responsible for setting the correct owner.

Can you show `systemctl -a | grep snap.lxd`?

**Comment by hadmut** [comment]
% systemctl -a | grep snap.lxd

  snap-lxd-21039.mount                                                                                                                                  loaded    active     mounted   Mount unit for lxd, revision 21039                                                                            
  snap-lxd-21260.mount                                                                                                                                  loaded    active     mounted   Mount unit for lxd, revision 21260                                                                            
  var-snap-lxd-common-ns-mntns.mount                                                                                                                    loaded    active     mounted   /var/snap/lxd/common/ns/mntns                                                                                 
  var-snap-lxd-common-ns-shmounts.mount                                                                                                                 loaded    active     mounted   /var/snap/lxd/common/ns/shmounts                                                                              
  var-snap-lxd-common-ns.mount                                                                                                                          loaded    active     mounted   /var/snap/lxd/common/ns                                                                                       
  snap.lxd.daemon.service                                                                                                                               loaded    active     running   Service for snap application lxd.daemon                                                                       
  snap.lxd.workaround.service                                                                                                                           loaded    active     exited    /bin/true                                                                                                     
  snap.lxd.daemon.unix.socket                                                                                                                           loaded    active     running   Socket unix for snap application lxd.daemon

**Comment by hadmut** [comment]
Good hint. 

Found the reason.

# snap services
Service               Startup   Current   Notes
lxd.activate          disabled  inactive  -
lxd.daemon            enabled   active    socket-activated



After reboot that control socket exists, but is used by process 1 = systemd-sysv only. lxd not running. 

When used for the very first time, systemd starts lxd. That's why it works when using lxc as root, just with a significant delay. 

Therefore,  once lxc used as root, it can be used by other members of group lxd as well. 

Comfortable, but still nasty, because this way it is hard to recognize, that it is sort of disabled.

**Comment by stgraber** [comment]
`systemctl enable snap.lxd.activate` should fix it.
This is a snapd bug, this unit should never get disabled. I'm going to close this issue as unfortunately there's not much we can do about it.

I'd recommend you report this issue at https://forum.snapcraft.io so hopefully snapd can be fixed to not randomly disabled units like this...
