### ISSUE TITLE
Use vim.basic in host instead of vim.tiny in snap ?

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd-pkg-snap#83]
I used LXD in my desktop environment without snap,
When I use `lxc file edit` I can take advantage of simple syntax coloration ;o)

But in my server environment with ubuntu snap, `lxc file edit` use vim.tiny embedded in LXD snap.

I tried to modify EDITOR variable in the host without success..

Is there a way to use vim.basic from host in place of vim.tiny in LXD snap package ?
Thanks a lot for my eyes ;o)

**Comment by aguytech** [comment]
Hi, thanks you for your complete explanation.
Have a good day 😊

**Comment by stgraber** [comment]
Just pushed an implementation of a built-in editor wrapper to the snap.
This also changes our fallback from `vim.tiny` to `nano` as the latter is far more user friendly :)

I've done some tests here and it's correctly running my host's vim and I can even run properly with EDITOR=gedit, but it will be interesting to see if we break anything with that as it's really really not straightforward to do this (see the commit link above) :)

**Comment by aguytech** [comment]
Hi, thanks a lot
I 'll try this when I back home. I'm in hospital for a surgery

**Comment by stgraber** [comment]
Hope it all goes well and that you're back home soon!

**Comment by aguytech** [comment]
Hi,

I'm not in a 100% state after surgery but I have to be patient ;o)

Sorry, I wrote a comment on the commit https://github.com/lxc/lxd-pkg-snap/commit/006c93a0a8b3a720143b1497cc239b87d40aed66#commitcomment-59074114
There is an issue with a declared editor from host :o(

Have a good day
